// SET RANDOM BRAND
export const SET_RANDOM_BRAND = 'SET_RANDOM_BRAND';

// Fetching multiple data from API
export const API_PHONE_INFO_SUCCESS = 'API_PHONE_INFO_SUCCESS';
export const API_PHONE_INFO_REQUEST = 'API_PHONE_INFO_REQUEST';
export const API_PHONE_INFO_ERROR = 'API_PHONE_INFO_ERROR';

// Store current match for future fetching
export const STORE_CURRENT_MATCH = 'STORE_CURRENT_MATCH';

// Fetching single data from API
export const API_SINGLE_PHONE_INFO_REQUEST = 'API_SINGLE_PHONE_INFO_REQUEST';
export const API_SINGLE_PHONE_INFO_SUCCESS = 'API_SINGLE_PHONE_INFO_SUCCESS';
export const API_SINGLE_PHONE_INFO_ERROR = 'API_SINGLE_PHONE_INFO_ERROR';

// -----------------------------
export const REQUEST_IMAGES = 'REQUEST_IMAGES';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';

// GETTING THE BRAND NAME
export const GET_BRAND_NAME = 'GET_BRAND_NAME';

// ADDING TO CART
export const ADD_PHONE_TO_CART = 'ADD_PHONE_TO_CART';
// DELETE CURRENT PHONE CART
export const DELETE_CURRENT_PHONE_CART = 'DELETE_CURRENT_PHONE_CART';
// CLEAR CART
export const CLEAR_CURRENT_CART = 'CLEAR_CURRENT_CART';
